### ISSUE TITLE
Workerize further

### ISSUE THREAD

**Issue by Veldhoen** [beeldengeluid/dane-visual-feature-extraction-worker#15]
- [x] Download input from S3 (see https://github.com/CLARIAH/DANE/issues/18) 
- [x] Concatenate provenance (depends on https://github.com/CLARIAH/DANE/issues/19)
- [x] Export output to S3
- [x] Logging & return meaningful Dane status code + message

**Comment by jblom** [comment]
The basics are done. The provenance data could be better checked though and also the error checking could be improved. Would like to run it first though to see if both workers can succesfully interact

**Comment by jblom** [comment]
working on provenance, which is described in this issue: https://github.com/CLARIAH/DANE/issues/19
